name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Publish with dotnet
      run: dotnet publish -r linux-arm -c Release -o publish/linux-arm

    - name: Run tests
      run: dotnet test
    
    - name: Write version
      run: 'echo "version $GITHUB_SHA" > publish/linux-arm/build.cfg'

    - uses: actions/upload-artifact@v1
      with:
        name: linux-arm
        path: publish/linux-arm
